language: node_js
node_js:
  - "lts/*"
  - "node"

#before_script: npm run lint
#script: npm run test
#after_success: npm run coveralls

install:
  - npm install

script:
  - npm test
  - npm run lint
  - npm run build
  - npm run debug:generator
  - npm run debug:write

branches:
  only:
    - master
